// lib/supabase.ts
// Supabase client configuration for Rize database

import { createClient } from '@supabase/supabase-js';

// Get Supabase configuration from environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables. Check .env file.');
}

/**
 * Supabase client for client-side and server-side operations
 * Uses anonymous key for public operations
 */
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Create a Supabase client with service role key for admin operations
 * Only use this in API routes or server-side code
 */
export function createServiceClient() {
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY;
  
  if (!supabaseUrl || !supabaseServiceKey) {
    throw new Error('Missing Supabase environment variables for service client');
  }
  
  return createClient(supabaseUrl, supabaseServiceKey);
}

// Database types (will be auto-generated by Supabase later)
export interface TopStartup {
  id: number;
  rank: number;
  name: string;
  founded_year: number;
  founder: string;
  valuation: string;
  description: string;
  category: string | null;
  logo_url: string | null;
}

export interface StartupVote {
  id: string;
  user_id: string;
  startup_id: number;
  market_opportunity: number;
  innovation: number;
  execution_difficulty: number;
  scalability: number;
  social_impact: number;
  created_at: string;
}

export interface StudentProject {
  id: string;
  user_id: string;
  user_email: string;
  user_name: string | null;
  user_class: string | null;
  project_name: string;
  tagline: string;
  description: string;
  industry: string;
  stage: string;
  team_size: number | null;
  website_url: string | null;
  demo_url: string | null;
  pitch_deck_url: string | null;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface ProjectVote {
  id: string;
  user_id: string;
  project_id: string;
  market_opportunity: number;
  innovation: number;
  execution_difficulty: number;
  scalability: number;
  social_impact: number;
  created_at: string;
}
